### ISSUE TITLE
[error] Error [ERR_INTERNAL_ASSERTION]

### ISSUE THREAD

**Issue by Brennok** [civitai/civitai-link-desktop#44]
With 1.16.0 and 1.16.1 I am seeing the below error. I had a few more with 1.16.0, but it looks like the old logs were overwritten already so might be worth expanding how many old logs are maintained for those of us with too many files. 

1.16.0 eventually got to a working state, but continued to run pretty heavily in the background. 1.16.1 never completed and just hung as unresponsive for a good hour or more before I closed it via the task manager. 

1.16.1
[2024-04-29 16:55:38.906] [error] Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:406:5)
    at assert (node:internal/assert:14:11)
    at internalConnectMultiple (node:net:1118:3)
    at afterConnectMultiple (node:net:1667:5)
    
    
[main 1.16.1.txt](https://github.com/civitai/civitai-link-desktop/files/15155367/main.1.16.1.txt)

**Comment by cmoody** [comment]
Looks like it might be an issue with Node 20 and socket connections. Nothing really changed there so not sure why it would just now show up. I think theres a fix in Node for it so let me see if maybe we need to upgrade that.

**Comment by cmoody** [comment]
@Brennok I updated things in 1.18.0 to specify the version of Node it uses. I think this should resolve the issue you are seeing. Test it out and let me know. Thanks!

**Comment by Brennok** [comment]
@cmoody I am still seeing the errors. Not noticing anything other than the initial delay during startup when it is scanning all files. I haven't run the desktop link since about two weeks ago so it had to do a pretty big refresh. 

It was showing disconnected with yellow so I tried to update the link key in case, but I had to wait for the scan to complete for it to save.

It does look like others had the same issue depending on node used, https://github.com/nodejs/node/issues/51354, guessing you probably saw this already, but in case and no idea if related. Same error though.

[main.old.txt](https://github.com/civitai/civitai-link-desktop/files/15339322/main.old.txt)
[main.log](https://github.com/civitai/civitai-link-desktop/files/15339325/main.log)

**Comment by cmoody** [comment]
@Brennok are you on WIndows NT? Im going down some rabbit holes on this. I found this issue https://github.com/nodejs/node/issues/50655 which I think might relate. Looking at Electron versions and their node compatibility. https://www.electronjs.org/docs/latest/tutorial/electron-timelines I set us to Node v20.12.2 but we are running Electron v29.1.6. Im thinking whats used to run dev is not how it gets compiled or theres still an error in the version of Node we are using.

Also found it might be fix in v20.13.1. Im going to try to upgrade Electron and Node and see if that helps.

**Comment by Brennok** [comment]
I am on Win 11 pro. Only seeing the errors in the log so not sure what if
any issues it might be having.

**Comment by cmoody** [comment]
@Brennok 1.20.0 Should have Node 20.13.1 which I think fixes this. 🤞
